[build]
    functions = "functions"

[[plugins]]
    package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
        customDomain = "www.moely.link"
        excludes = ["**/page/**","**/category/**","**/user/**","/"]
