[build]
    functions = "functions"

[[plugins]]
    package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
        exclude = ["**/page/**","**/category/**","**/user/**","/"]
        customDomain = "www.moely.link"
